-- MySQL Script generated by MySQL Workbench
-- 06/17/14 14:12:28
-- Model: New Model    Version: 1.0
USE mshattil;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 361Project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users`;
CREATE TABLE `Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pictures`;
CREATE TABLE `Pictures` (
  `PictureID` INT NOT NULL AUTO_INCREMENT,
  `File` VARCHAR(45) NOT NULL,
  `Caption` VARCHAR(255) NULL,
  `Latitude` VARCHAR(45) NOT NULL,
  `Longitutde` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PictureID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comments`;
CREATE TABLE `Comments` (
  `CommentID` INT NOT NULL AUTO_INCREMENT,
  `Message` VARCHAR(255) NOT NULL,
  `PictureID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`CommentID`),
	FOREIGN KEY (`PictureID`) REFERENCES Pictures (`PictureID`),
    FOREIGN KEY (`userID`) REFERENCES Users (`UserID`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
